# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: feizao_睡眠赚

on:
  workflow_dispatch:
  schedule:
    - cron: '11 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install


      - name: '运行 【睡眠赚1】'
        run: |
          node ./workflow/feizao/smz1.js
        env:
          TZ: Asia/shanghai



      - name: '运行 【睡眠赚2】'
        run: |
          node ./workflow/feizao/smz2.js
        env:
          TZ: Asia/shanghai
