# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: sunert_腾讯新闻

on:
  workflow_dispatch:
  schedule:
    - cron: '10 16 * * *'

jobs:
  build:
    env:
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install



      - name: '运行 【腾讯新闻】'
        run: |
          node ./workflow/sunert/txnews.js
        env:
          TZ: Asia/shanghai





