# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 百度极速版

on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 * * * *'

jobs:
  build:
    env:
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install



      - name: '运行 【百度极速版】'
        run: |
          node ./workflow/sunert/baidu_speed.js
        env:
          TZ: Asia/shanghai
          BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
          BAIDU_CASH: ${{ secrets.BAIDU_CASH }}





