# File: .github/workflows/repo-sync.yml
name: sync_repo
on:
  workflow_dispatch:
  schedule:
    - cron: '30 */6 * * *'

jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync sync-ziye
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ziye11/JavaScript.git"
          source_branch: "main"
          destination_branch: "ziye"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}


      - name: sync sync-zhiyi
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZhiYi-N/Private-Script.git"
          source_branch: "master"
          destination_branch: "zhiyi"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}


      - name: sync sync-hundun
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/hundun.git"
          source_branch: "master"
          destination_branch: "hundun"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}


