# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青阅读

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install


      - name: '运行 【中青阅读1】'
        run: |
          node ./workflow/youth/youth_Read1.js
        env:
          TZ: Asia/shanghai


      - name: '运行 【中青阅读2】'
        run: |
          node ./workflow/youth/youth_Read2.js
        env:
          TZ: Asia/shanghai


      - name: '运行 【中青阅读_混合】'
        run: |
          node ./workflow/youth/youth_Read_mix.js
        env:
          TZ: Asia/shanghai
