# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东循环任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job
jobs:
  build:
    env:
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.JD_COOKIE
        run: |
          ${{ secrets.JD_HTTPS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.JD_COOKIE
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.JD_COOKIE
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.JD_COOKIE
        run: |
          cd ~/TaskAction
          git checkout master
          npm install

      - name: '运行 【京东种豆得豆】'
        run: |
          cd ~/TaskAction
          node jd_plantBean.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PLANT_BEAN_SHARECODES: ${{ secrets.PLANT_BEAN_SHARECODES }}
#          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: '运行 【东东农场】'
        run: |
          cd ~/TaskAction
          node jd_fruit.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          FRUITSHARECODES: ${{ secrets.FRUITSHARECODES }}
#          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【东东工厂】'
        run: |
          cd ~/TaskAction
          node jd_jdfactory.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
#          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【京喜农场】'
        run: |
          cd ~/TaskAction
          node jd_jxnc.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
          JXNC_SHARECODES: ${{ secrets.JXNC_SHARECODES }}
#          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: '运行 【京喜工厂】'
        run: |
          cd ~/TaskAction
          node jd_dreamFactory.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          JXNCTOKENS: ${{ secrets.JXNCTOKENS }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }}
#          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【东东萌宠】'
        run: |
          cd ~/TaskAction
          node jd_pet.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PETSHARECODES: ${{ secrets.PETSHARECODES }}
#          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【东东超市】'
        run: |
          cd ~/TaskAction
          node jd_superMarket.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: '运行 【口袋书店】'
        run: |
          cd ~/TaskAction
          node jd_bookshop.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【宠汪汪积分兑换奖品】'
        run: |
          cd ~/TaskAction
          node jd_joy_reward.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【宠汪汪偷好友积分与狗】'
        run: |
          cd ~/TaskAction
          node jd_joy_steal.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: '运行 【点点券】'
        run: |
          cd ~/TaskAction
          node jd_necklace.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【取关京东店铺商品】'
        run: |
          cd ~/TaskAction
          node jd_unsubscribe.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【京东天天加速】'
        run: |
          cd ~/TaskAction
          node jd_speed.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【天天提鹅】'
        run: |
          cd ~/TaskAction
          node jd_daily_egg.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

      - name: '运行 【crazyJoy任务】'
        run: |
          cd ~/TaskAction
          node jd_crazy_joy.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}


      - name: '运行 【美丽研究院】'
        run: |
          cd ~/TaskAction
          node jd_beauty.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}



