# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京东定时任务

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

jobs:
  build:
    env:
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          ${{ secrets.JD_HTTPS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/TaskAction
          git checkout master
          npm install

      - name: '运行 【签到】'
        run: |
          cd ~/TaskAction
          node jd_bean_sign.js


      - name: '运行 【京喜签到】'
        run: |
          cd ~/TaskAction
          node jx_sign.js


      - name: '运行 【京小超兑换奖品】'
        run: |
          cd ~/TaskAction
          node jd_blueCoin.js


      - name: '运行 【摇京豆】'
        run: |
          cd ~/TaskAction
          node jd_club_lottery.js


      - name: '运行 【领京豆额外奖励】'
        run: |
          cd ~/TaskAction
          node jd_bean_home.js


      - name: '运行 【京东全民开红包】'
        run: |
          cd ~/TaskAction
          node jd_redPacket.js


      - name: '运行 【进店领豆】'
        run: |
          cd ~/TaskAction
          node jd_shop.js


      - name: '运行 【签到领现金】'
        run: |
          cd ~/TaskAction
          node jd_cash.js
        env:
          JD_CASH_SHARECODES: ${{ secrets.JD_CASH_SHARECODES }}

      - name: '运行 【京东汽车】'
        run: |
          cd ~/TaskAction
          node jd_car.js


      - name: '运行 【京东汽车】'
        run: |
          cd ~/TaskAction
          node jd_car_exchange.js


      - name: '运行 【东东小窝】'
        run: |
          cd ~/TaskAction
          node jd_small_home.js


      - name: '运行 【疯狂的joy】'
        run: |
          cd ~/TaskAction
          node jd_crazy_joy.js


      - name: '运行 【金融养猪】'
        run: |
          cd ~/TaskAction
          node jd_pigPet.js


      - name: '运行 【十元街】'
        run: |
          cd ~/TaskAction
          node jd_syj.js


      - name: '运行 【京东快递】'
        run: |
          cd ~/TaskAction
          node jd_kd.js


      - name: '运行 【京东赚赚】'
        run: |
          cd ~/TaskAction
          node jd_jdzz.js


      - name: '运行 【盲盒抽京豆】'
        run: |
          cd ~/TaskAction
          node jd_sgmh.js


      - name: '运行 【京东秒秒币】'
        run: |
          cd ~/TaskAction
          node jd_ms.js



