# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 测试11

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'
  watch:
    types: started
  repository_dispatch:
    types: jd_job

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          ${{ secrets.JD_HTTPS }}
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install


      - name: '运行 【取关京东店铺商品】'
        run: |
          cd ~/TaskAction
          node jd_unsubscribe.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}

 

