# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 抖音火山版

on:
  workflow_dispatch:
  schedule:
    - cron: '5 */6 * * *' # UTC时间 +8 北京时间
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install

      - name: '运行 【抖音火山版】'
        run: |
          node ./workflow/huoshan.js
        env:
          TZ: Asia/shanghai
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
