# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 芝嫲视频

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'
  watch:
    types: started

jobs:
  build:
    env:
      ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        if: env.ZM_zhimabody
        run: |
          ${{ secrets.ZY_HTTPS }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        if: env.ZM_zhimabody
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        if: env.ZM_zhimabody
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.ZM_zhimabody
        run: |
          cd ~/JavaScript
          git checkout main
          npm install

      - name: '运行 【芝嫲视频】'
        run: |
          cd ~/JavaScript/Task
          node zhima.js
        env:
          ZM_zhimabody: ${{ secrets.ZM_zhimabody }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}